# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100'

- task: UseNode@1
  inputs:
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj' 
    verbosityRestore: 'Quiet'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'      
    arguments: '-c $(BuildConfiguration)'

- task: Npm@1
  displayName: 'npm install vue cli'
  inputs:
    command: custom
    workingDir: src/SIO-Web/app
    verbose: false
    customCommand: 'install @vue/cli@">=3.0.0 <4.0.0" -g'

- task: Npm@1
  displayName: 'npm install packages'
  inputs:
    workingDir: src/SIO-Web/app
    verbose: false

- task: Npm@1
  displayName: 'npm rebuild sass'
  inputs:
    command: custom
    workingDir: src/SIO-Web/app
    verbose: false
    customCommand: 'rebuild node-sass'

- task: Npm@1
  displayName: 'npm build vue app'
  inputs:
    command: custom
    workingDir: src/SIO-Web/app
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm run unit tests'
  inputs:
    command: custom
    workingDir: src/SIO-Web/app
    verbose: false
    customCommand: 'run test:unit'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'